baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Quarterly Calender'

disableKinds = ['taxonomy', 'sitemap' ]
  
[security]
	[security.exec]
		allow = ['^go$', '^npx$', '^postcss$', '^babel$']
