baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

disableKinds = ['taxonomyTerm', 'sitemap' ]
  
[security]
	[security.exec]
		allow = ['^go$', '^npx$', '^postcss$', '^babel$']